// <auto-generated />
using Gabriel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gabriel.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("Gabriel.Models.ConsumoDeAgua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AdicionalBandeira")
                        .HasColumnType("REAL");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bandeira")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ConsumoFaturado")
                        .HasColumnType("REAL");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("M3Consumidos")
                        .HasColumnType("REAL");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PossuiEsgoto")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Tarifa")
                        .HasColumnType("REAL");

                    b.Property<double>("TaxaEsgoto")
                        .HasColumnType("REAL");

                    b.Property<double>("Total")
                        .HasColumnType("REAL");

                    b.Property<int>("ValorAgua")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ConsumoDeAguas");
                });
#pragma warning restore 612, 618
        }
    }
}
